### PR TITLE
Adding items to Leas shopping list fixes issue #13

### PR DESCRIPTION
**Pull request by LChWu**
Adds food and drinks for board game night to [Leas shopping list](https://github.com/pbuttigieg/shoppingList/blob/main/lists/shoppinglistLea.txt) fixing issue #13

### CODE REVIEW

**Comment by LChWu** [comment]
@gdangelo8 could you please review this shopping list

**Review by gdangelo8 — CHANGES_REQUESTED** [review]
Please update the list as noted in the comments I wrote

**Review by gdangelo8 — APPROVED** [review]
Thank you for the updates

**Comment by LChWu** [comment]
Thank you for reviewing @gdangelo8, I will merge the branch now

**Pull request merged**
