### PR TITLE
Add Ringing Equipment to my shopping list

### PR DESCRIPTION
**Pull request by tobiaswoldt**
Here my updated shopping list for Bird Catching #15

### CODE REVIEW

**Comment by LChWu** [comment]
Please remove the empty file https://github.com/pbuttigieg/shoppingList/pull/22/files#diff-4e85a6c5ec7ec2521be66f2493ecb639d1edc0b17175db1cc48d17bc63a8a22f

**Review by LChWu — CHANGES_REQUESTED** [review]
@tobiaswoldt please remove the empty file

**Review by pbuttigieg — CHANGES_REQUESTED** [review]
@tobiaswoldt please remove the top level file tobisShoppingList.txt, as noted by @LChWu

**Review by LChWu — APPROVED** [review]
@tobiaswoldt everything looks good now 👍

**Review by pbuttigieg — APPROVED** [review]

**Pull request merged**
